server:
  port: 8000



logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG

#  测试账号
wx:
  mp:
    configs:
      - appId: wxae9367e1c7c92340
        secret: 4c57f5cec343e8b8b0ea027001f3db72
        token: test001
        aesKey:

###########公司账号
#wx:
#  mp:
#    configs:
#      - appId: wx9c03594d12f6f7f9
#        secret: c9f16a7481e7ce2172d76bc54a727727
#        token:
#        aesKey:

###########公司测试账号
#wx:
#  mp:
#    configs:
#      - appId: wxef71f21560c1e216
#        secret: 266c1e53ab86232a5b1fb8d8d405daaf
#        token:
#        aesKey:

###########春风账号
#wx:
#  mp:
#    configs:
#      - appId: wxf0fdd8ddad8b2e6f
#        secret: 4e5444793011ea5be9191a37aa33d928
#        token:
#        aesKey:


###########个人订阅号
#wx:
#  mp:
#    configs:
#      - appId:  wxeb25118b825602db
#        secret:  5fa452c2db11f37ab7830d9746fbabb3
#        token: test001
#        aesKey:


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    refresh-mapper: true
  mapper-locations: classpath:mybatis/*.xml
  typeAliasesPackage: com.github.binarywang.demo.wx.mp.entity


#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://127.0.0.1:3306/cdp_swarovski?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 100
      minimum-idle: 10
      pool-name: DatebookHikariCP
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/chunjieboot?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: root